name: Release

on:
  push:
    branches:
      - main
    paths:
      - '.changeset/**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write # to create release (changesets/action)
  issues: write # to post issue comments (changesets/action)
  pull-requests: write # to create pull request (changesets/action)
  id-token: write

jobs:
  release:
    environment: release
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
          version: pnpm changeset version
          commit: 'chore: new release'
          title: 'chore: new release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy docs
        run: cd docs && pnpm deploy
